In [8]:
def multi_hot(x, num_classes):
    return tf.reduce_sum(tf.one_hot(x, num_classes), -2)


In [9]:
x= [1, 3, 0] 
num_classes =4

In [10]:
multi_hot(x, num_classes)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 0., 1.], dtype=float32)>

In [11]:
import tensorflow as tf

In [12]:
tf.one_hot(x, num_classes)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]], dtype=float32)>